name = "LeanToolkit"
version = "0.1.0"
testDriver = "Test"
defaultTargets = ["LeanToolkit"]

[[lean_lib]]
name = "LeanToolkit"

[[lean_lib]]
name = "CaseStudy"
srcDir = "CaseStudy"

[[lean_lib]]
name = "Test"
